### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by shyan0903**

### CODE REVIEW

**Review by BooleanJulien — CHANGES_REQUESTED** [review]
Hi @shyan0903 not sure if this is the final version or not but I think ithe sections that are here are a bit threadbare and its missing a few elements that were requested in the Milestone 2 requirements. 

I'd suggest taking a look at the milestone 2 section 5 guidelines and following the example repos that she provided a bit more closely.

Just a heads up they request a table of contents and a gif that are not here. 

Let us know if you need any help with this. 
https://pages.github.ubc.ca/mds-2021-22/DSCI_532_viz-2_students/materials/release/milestone2/milestone2.html
image

**Comment by shyan0903** [comment]
Hi @BooleanJulien, I just added a toc and a gif! Thank you for the review!

**Review by imtvwy — CHANGES_REQUESTED** [review]
@shyan0903 
- Do you mind to move the heroku link to the top of the README to make it prominent as requested in the M2 reqt?
- It seems that the gif haven't captured the most recent layout change (guess not deployed to Heroku yet?)  Maybe you can pull the main branch and get the gif from your local?  (The Flip button is made diff of the other buttons and a Back button is added in the back card)

**Comment by SonQBChau** [comment]
let me update heroku first

**Comment by SonQBChau** [comment]
It is up-to-date. Also, I recommend https://ezgif.com/ to convert and resize the gif to smaller size

**Comment by shyan0903** [comment]
@imtvwy Hi Vanessa, I've updated the gif and moved the link to the top. @SonQBChau  Thank you for your help! I've made the installation part TODO as instructed by Florencia.

**Comment by imtvwy** [comment]
@shyan0903 Do you think we should remove the sketch if we have added the gif?  I'm not sure. Maybe replace the sketch with the gif under the Dashboard Description?  (Leave the link at the top)   
Agree with Son, I think resizing the gif will make the README more readable.

**Comment by shyan0903** [comment]
@imtvwy I'm not sure about removing the sketch as I checked out some of the other groups' repo and they kept it. As for resizing the gif, as I still have one lab left, I will prioritize that and work on resizing next week. Does that sound good with you? Thank you for the understanding!

**Comment by imtvwy** [comment]
> @imtvwy I'm not sure about removing the sketch as I checked out some of the other groups' repo and they kept it. As for resizing the gif, as I still have one lab left, I will prioritize that and work on resizing next week. Does that sound good with you? Thank you for the understanding!

Not a problem, I can help for the resizing.

**Review by imtvwy — APPROVED** [review]

**Pull request merged**
